/*
 * ShopApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.FileParameter;
using OpenAPIDateConverter = ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.OpenAPIDateConverter;
using OpenAPIClientUtils = ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ClientUtils;

namespace ShopWeb.Domain.Models
{
    /// <summary>
    /// Defines ELoginType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ELoginType
    {
        /// <summary>
        /// Enum Mobile for value: Mobile
        /// </summary>
        [EnumMember(Value = "Mobile")]
        Mobile = 1,

        /// <summary>
        /// Enum Web for value: Web
        /// </summary>
        [EnumMember(Value = "Web")]
        Web = 2,

        /// <summary>
        /// Enum External for value: External
        /// </summary>
        [EnumMember(Value = "External")]
        External = 3
    }

}



