/*
 * ShopApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;

namespace ShopWeb.Domain.Models
{
    /// <summary>
    /// Inventory
    /// </summary>
    [DataContract(Name = "Inventory")]
    public partial class Inventory : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Inventory" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="name">name.</param>
        /// <param name="type">type.</param>
        /// <param name="executeWay">executeWay.</param>
        /// <param name="responsiblePerson">responsiblePerson.</param>
        /// <param name="companyName">companyName.</param>
        /// <param name="companyAddress">companyAddress.</param>
        /// <param name="comissionTeam">comissionTeam.</param>
        /// <param name="personToValue">personToValue.</param>
        /// <param name="personToCheck">personToCheck.</param>
        /// <param name="createdAt">createdAt.</param>
        /// <param name="startDate">startDate.</param>
        /// <param name="endDate">endDate.</param>
        /// <param name="createdByUserId">createdByUserId.</param>
        /// <param name="inventoryStatusId">inventoryStatusId.</param>
        /// <param name="createdByUser">createdByUser.</param>
        /// <param name="inventoryStatus">inventoryStatus.</param>
        public Inventory(int id = default, string name = default, string type = default, string executeWay = default, string responsiblePerson = default, string companyName = default, string companyAddress = default, string comissionTeam = default, string personToValue = default, string personToCheck = default, DateTime createdAt = default, DateTime startDate = default, DateTime? endDate = default, int createdByUserId = default, int inventoryStatusId = default, User createdByUser = default, InventoryStatus inventoryStatus = default)
        {
            this.Id = id;
            this.Name = name;
            this.Type = type;
            this.ExecuteWay = executeWay;
            this.ResponsiblePerson = responsiblePerson;
            this.CompanyName = companyName;
            this.CompanyAddress = companyAddress;
            this.ComissionTeam = comissionTeam;
            this.PersonToValue = personToValue;
            this.PersonToCheck = personToCheck;
            this.CreatedAt = createdAt;
            this.StartDate = startDate;
            this.EndDate = endDate;
            this.CreatedByUserId = createdByUserId;
            this.InventoryStatusId = inventoryStatusId;
            this.CreatedByUser = createdByUser;
            this.InventoryStatus = inventoryStatus;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public int Id { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", EmitDefaultValue = true)]
        public string Type { get; set; }

        /// <summary>
        /// Gets or Sets ExecuteWay
        /// </summary>
        [DataMember(Name = "executeWay", EmitDefaultValue = true)]
        public string ExecuteWay { get; set; }

        /// <summary>
        /// Gets or Sets ResponsiblePerson
        /// </summary>
        [DataMember(Name = "responsiblePerson", EmitDefaultValue = true)]
        public string ResponsiblePerson { get; set; }

        /// <summary>
        /// Gets or Sets CompanyName
        /// </summary>
        [DataMember(Name = "companyName", EmitDefaultValue = true)]
        public string CompanyName { get; set; }

        /// <summary>
        /// Gets or Sets CompanyAddress
        /// </summary>
        [DataMember(Name = "companyAddress", EmitDefaultValue = true)]
        public string CompanyAddress { get; set; }

        /// <summary>
        /// Gets or Sets ComissionTeam
        /// </summary>
        [DataMember(Name = "comissionTeam", EmitDefaultValue = true)]
        public string ComissionTeam { get; set; }

        /// <summary>
        /// Gets or Sets PersonToValue
        /// </summary>
        [DataMember(Name = "personToValue", EmitDefaultValue = true)]
        public string PersonToValue { get; set; }

        /// <summary>
        /// Gets or Sets PersonToCheck
        /// </summary>
        [DataMember(Name = "personToCheck", EmitDefaultValue = true)]
        public string PersonToCheck { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [DataMember(Name = "createdAt", EmitDefaultValue = false)]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets StartDate
        /// </summary>
        [DataMember(Name = "startDate", EmitDefaultValue = false)]
        public DateTime StartDate { get; set; }

        /// <summary>
        /// Gets or Sets EndDate
        /// </summary>
        [DataMember(Name = "endDate", EmitDefaultValue = true)]
        public DateTime? EndDate { get; set; }

        /// <summary>
        /// Gets or Sets CreatedByUserId
        /// </summary>
        [DataMember(Name = "createdByUserId", EmitDefaultValue = false)]
        public int CreatedByUserId { get; set; }

        /// <summary>
        /// Gets or Sets InventoryStatusId
        /// </summary>
        [DataMember(Name = "inventoryStatusId", EmitDefaultValue = false)]
        public int InventoryStatusId { get; set; }

        /// <summary>
        /// Gets or Sets CreatedByUser
        /// </summary>
        [DataMember(Name = "createdByUser", EmitDefaultValue = false)]
        public User? CreatedByUser { get; set; }

        /// <summary>
        /// Gets or Sets InventoryStatus
        /// </summary>
        [DataMember(Name = "inventoryStatus", EmitDefaultValue = false)]
        public InventoryStatus? InventoryStatus { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Inventory {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  ExecuteWay: ").Append(ExecuteWay).Append("\n");
            sb.Append("  ResponsiblePerson: ").Append(ResponsiblePerson).Append("\n");
            sb.Append("  CompanyName: ").Append(CompanyName).Append("\n");
            sb.Append("  CompanyAddress: ").Append(CompanyAddress).Append("\n");
            sb.Append("  ComissionTeam: ").Append(ComissionTeam).Append("\n");
            sb.Append("  PersonToValue: ").Append(PersonToValue).Append("\n");
            sb.Append("  PersonToCheck: ").Append(PersonToCheck).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  StartDate: ").Append(StartDate).Append("\n");
            sb.Append("  EndDate: ").Append(EndDate).Append("\n");
            sb.Append("  CreatedByUserId: ").Append(CreatedByUserId).Append("\n");
            sb.Append("  InventoryStatusId: ").Append(InventoryStatusId).Append("\n");
            sb.Append("  CreatedByUser: ").Append(CreatedByUser).Append("\n");
            sb.Append("  InventoryStatus: ").Append(InventoryStatus).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}


