/*
 * ShopApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;

namespace ShopWeb.Domain.Models
{
    /// <summary>
    /// InventoryPosition
    /// </summary>
    [DataContract(Name = "InventoryPosition")]
    public partial class InventoryPosition : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InventoryPosition" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="quantity">quantity.</param>
        /// <param name="price">price.</param>
        /// <param name="scanDate">scanDate.</param>
        /// <param name="productId">productId.</param>
        /// <param name="userId">userId.</param>
        /// <param name="inventoryId">inventoryId.</param>
        /// <param name="modifiedByUserId">modifiedByUserId.</param>
        /// <param name="product">product.</param>
        /// <param name="user">user.</param>
        /// <param name="modifiedByUser">modifiedByUser.</param>
        /// <param name="inventory">inventory.</param>
        public InventoryPosition(int id = default, double quantity = default, double price = default, DateTime scanDate = default, int productId = default, int userId = default, int inventoryId = default, int? modifiedByUserId = default, Product product = default, User user = default, User modifiedByUser = default, Inventory inventory = default)
        {
            this.Id = id;
            this.Quantity = quantity;
            this.Price = price;
            this.ScanDate = scanDate;
            this.ProductId = productId;
            this.UserId = userId;
            this.InventoryId = inventoryId;
            this.ModifiedByUserId = modifiedByUserId;
            this.Product = product;
            this.User = user;
            this.ModifiedByUser = modifiedByUser;
            this.Inventory = inventory;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public int Id { get; set; }

        /// <summary>
        /// Gets or Sets Quantity
        /// </summary>
        [DataMember(Name = "quantity", EmitDefaultValue = false)]
        public double Quantity { get; set; }

        /// <summary>
        /// Gets or Sets Price
        /// </summary>
        [DataMember(Name = "price", EmitDefaultValue = false)]
        public double Price { get; set; }

        /// <summary>
        /// Gets or Sets ScanDate
        /// </summary>
        [DataMember(Name = "scanDate", EmitDefaultValue = false)]
        public DateTime ScanDate { get; set; }

        /// <summary>
        /// Gets or Sets ProductId
        /// </summary>
        [DataMember(Name = "productId", EmitDefaultValue = false)]
        public int ProductId { get; set; }

        /// <summary>
        /// Gets or Sets UserId
        /// </summary>
        [DataMember(Name = "userId", EmitDefaultValue = false)]
        public int UserId { get; set; }

        /// <summary>
        /// Gets or Sets InventoryId
        /// </summary>
        [DataMember(Name = "inventoryId", EmitDefaultValue = false)]
        public int InventoryId { get; set; }

        /// <summary>
        /// Gets or Sets ModifiedByUserId
        /// </summary>
        [DataMember(Name = "modifiedByUserId", EmitDefaultValue = true)]
        public int? ModifiedByUserId { get; set; }

        /// <summary>
        /// Gets or Sets Product
        /// </summary>
        [DataMember(Name = "product", EmitDefaultValue = false)]
        public Product Product { get; set; }

        /// <summary>
        /// Gets or Sets User
        /// </summary>
        [DataMember(Name = "user", EmitDefaultValue = false)]
        public User User { get; set; }

        /// <summary>
        /// Gets or Sets ModifiedByUser
        /// </summary>
        [DataMember(Name = "modifiedByUser", EmitDefaultValue = false)]
        public User ModifiedByUser { get; set; }

        /// <summary>
        /// Gets or Sets Inventory
        /// </summary>
        [DataMember(Name = "inventory", EmitDefaultValue = false)]
        public Inventory Inventory { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class InventoryPosition {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Quantity: ").Append(Quantity).Append("\n");
            sb.Append("  Price: ").Append(Price).Append("\n");
            sb.Append("  ScanDate: ").Append(ScanDate).Append("\n");
            sb.Append("  ProductId: ").Append(ProductId).Append("\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  InventoryId: ").Append(InventoryId).Append("\n");
            sb.Append("  ModifiedByUserId: ").Append(ModifiedByUserId).Append("\n");
            sb.Append("  Product: ").Append(Product).Append("\n");
            sb.Append("  User: ").Append(User).Append("\n");
            sb.Append("  ModifiedByUser: ").Append(ModifiedByUser).Append("\n");
            sb.Append("  Inventory: ").Append(Inventory).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}


