/*
 * ShopApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.FileParameter;
using OpenAPIDateConverter = ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.OpenAPIDateConverter;
using OpenAPIClientUtils = ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ClientUtils;

namespace ShopWeb.Domain.Models
{
    /// <summary>
    /// RegisterModel
    /// </summary>
    [DataContract(Name = "RegisterModel")]
    public partial class RegisterModel : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RegisterModel" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RegisterModel() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RegisterModel" /> class.
        /// </summary>
        /// <param name="name">name (required).</param>
        /// <param name="surname">surname (required).</param>
        /// <param name="username">username (required).</param>
        /// <param name="email">email (required).</param>
        /// <param name="password">password (required).</param>
        /// <param name="confirmPassword">confirmPassword (required).</param>
        public RegisterModel(string name = default, string surname = default, string username = default, string email = default, string password = default, string confirmPassword = default)
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for RegisterModel and cannot be null");
            }
            this.Name = name;
            // to ensure "surname" is required (not null)
            if (surname == null)
            {
                throw new ArgumentNullException("surname is a required property for RegisterModel and cannot be null");
            }
            this.Surname = surname;
            // to ensure "username" is required (not null)
            if (username == null)
            {
                throw new ArgumentNullException("username is a required property for RegisterModel and cannot be null");
            }
            this.Username = username;
            // to ensure "email" is required (not null)
            if (email == null)
            {
                throw new ArgumentNullException("email is a required property for RegisterModel and cannot be null");
            }
            this.Email = email;
            // to ensure "password" is required (not null)
            if (password == null)
            {
                throw new ArgumentNullException("password is a required property for RegisterModel and cannot be null");
            }
            this.Password = password;
            // to ensure "confirmPassword" is required (not null)
            if (confirmPassword == null)
            {
                throw new ArgumentNullException("confirmPassword is a required property for RegisterModel and cannot be null");
            }
            this.ConfirmPassword = confirmPassword;
        }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Surname
        /// </summary>
        [DataMember(Name = "surname", IsRequired = true, EmitDefaultValue = true)]
        public string Surname { get; set; }

        /// <summary>
        /// Gets or Sets Username
        /// </summary>
        [DataMember(Name = "username", IsRequired = true, EmitDefaultValue = true)]
        public string Username { get; set; }

        /// <summary>
        /// Gets or Sets Email
        /// </summary>
        [DataMember(Name = "email", IsRequired = true, EmitDefaultValue = true)]
        public string Email { get; set; }

        /// <summary>
        /// Gets or Sets Password
        /// </summary>
        [DataMember(Name = "password", IsRequired = true, EmitDefaultValue = true)]
        public string Password { get; set; }

        /// <summary>
        /// Gets or Sets ConfirmPassword
        /// </summary>
        [DataMember(Name = "confirmPassword", IsRequired = true, EmitDefaultValue = true)]
        public string ConfirmPassword { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RegisterModel {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Surname: ").Append(Surname).Append("\n");
            sb.Append("  Username: ").Append(Username).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  Password: ").Append(Password).Append("\n");
            sb.Append("  ConfirmPassword: ").Append(ConfirmPassword).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Name (string) maxLength
            if (this.Name != null && this.Name.Length > 50)
            {
                yield return new ValidationResult("Invalid value for Name, length must be less than 50.", new [] { "Name" });
            }

            // Name (string) minLength
            if (this.Name != null && this.Name.Length < 0)
            {
                yield return new ValidationResult("Invalid value for Name, length must be greater than 0.", new [] { "Name" });
            }

            // Surname (string) maxLength
            if (this.Surname != null && this.Surname.Length > 50)
            {
                yield return new ValidationResult("Invalid value for Surname, length must be less than 50.", new [] { "Surname" });
            }

            // Surname (string) minLength
            if (this.Surname != null && this.Surname.Length < 0)
            {
                yield return new ValidationResult("Invalid value for Surname, length must be greater than 0.", new [] { "Surname" });
            }

            // Username (string) maxLength
            if (this.Username != null && this.Username.Length > 50)
            {
                yield return new ValidationResult("Invalid value for Username, length must be less than 50.", new [] { "Username" });
            }

            // Username (string) minLength
            if (this.Username != null && this.Username.Length < 3)
            {
                yield return new ValidationResult("Invalid value for Username, length must be greater than 3.", new [] { "Username" });
            }

            // Email (string) minLength
            if (this.Email != null && this.Email.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Email, length must be greater than 1.", new [] { "Email" });
            }

            // Password (string) maxLength
            if (this.Password != null && this.Password.Length > 100)
            {
                yield return new ValidationResult("Invalid value for Password, length must be less than 100.", new [] { "Password" });
            }

            // Password (string) minLength
            if (this.Password != null && this.Password.Length < 6)
            {
                yield return new ValidationResult("Invalid value for Password, length must be greater than 6.", new [] { "Password" });
            }

            // ConfirmPassword (string) minLength
            if (this.ConfirmPassword != null && this.ConfirmPassword.Length < 1)
            {
                yield return new ValidationResult("Invalid value for ConfirmPassword, length must be greater than 1.", new [] { "ConfirmPassword" });
            }

            yield break;
        }
    }

}


