/*
 * ShopApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.FileParameter;
using OpenAPIDateConverter = ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.OpenAPIDateConverter;
using OpenAPIClientUtils = ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ClientUtils;

namespace ShopWeb.Domain.Models.Generated
{
    /// <summary>
    /// RoleForUser
    /// </summary>
    [DataContract(Name = "RoleForUser")]
    public partial class RoleForUser : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RoleForUser" /> class.
        /// </summary>
        /// <param name="userId">userId.</param>
        /// <param name="userRoleId">userRoleId.</param>
        /// <param name="user">user.</param>
        /// <param name="userRole">userRole.</param>
        public RoleForUser(int userId = default, int userRoleId = default, User user = default, UserRole userRole = default)
        {
            this.UserId = userId;
            this.UserRoleId = userRoleId;
            this.User = user;
            this.UserRole = userRole;
        }

        /// <summary>
        /// Gets or Sets UserId
        /// </summary>
        [DataMember(Name = "userId", EmitDefaultValue = false)]
        public int UserId { get; set; }

        /// <summary>
        /// Gets or Sets UserRoleId
        /// </summary>
        [DataMember(Name = "userRoleId", EmitDefaultValue = false)]
        public int UserRoleId { get; set; }

        /// <summary>
        /// Gets or Sets User
        /// </summary>
        [DataMember(Name = "user", EmitDefaultValue = false)]
        public User User { get; set; }

        /// <summary>
        /// Gets or Sets UserRole
        /// </summary>
        [DataMember(Name = "userRole", EmitDefaultValue = false)]
        public UserRole UserRole { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RoleForUser {\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  UserRoleId: ").Append(UserRoleId).Append("\n");
            sb.Append("  User: ").Append(User).Append("\n");
            sb.Append("  UserRole: ").Append(UserRole).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}


