/*
 * ShopApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;

namespace ShopWeb.Domain.Models
{
    /// <summary>
    /// SummaryInventoryPosition
    /// </summary>
    [DataContract(Name = "SummaryInventoryPosition")]
    public partial class SummaryInventoryPosition : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SummaryInventoryPosition" /> class.
        /// </summary>
        /// <param name="productName">productName.</param>
        /// <param name="quantity">quantity.</param>
        /// <param name="unit">unit.</param>
        /// <param name="price">price.</param>
        /// <param name="dateOfScanOrModification">dateOfScanOrModification.</param>
        public SummaryInventoryPosition(string productName = default, double quantity = default, string unit = default, double price = default, DateTime dateOfScanOrModification = default)
        {
            this.ProductName = productName;
            this.Quantity = quantity;
            this.Unit = unit;
            this.Price = price;
            this.DateOfScanOrModification = dateOfScanOrModification;
        }

        /// <summary>
        /// Gets or Sets ProductName
        /// </summary>
        [DataMember(Name = "productName", EmitDefaultValue = true)]
        public string ProductName { get; set; }

        /// <summary>
        /// Gets or Sets Quantity
        /// </summary>
        [DataMember(Name = "quantity", EmitDefaultValue = false)]
        public double Quantity { get; set; }

        /// <summary>
        /// Gets or Sets Unit
        /// </summary>
        [DataMember(Name = "unit", EmitDefaultValue = true)]
        public string Unit { get; set; }

        /// <summary>
        /// Gets or Sets Price
        /// </summary>
        [DataMember(Name = "price", EmitDefaultValue = false)]
        public double Price { get; set; }

        /// <summary>
        /// Gets or Sets DateOfScanOrModification
        /// </summary>
        [DataMember(Name = "dateOfScanOrModification", EmitDefaultValue = false)]
        public DateTime DateOfScanOrModification { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SummaryInventoryPosition {\n");
            sb.Append("  ProductName: ").Append(ProductName).Append("\n");
            sb.Append("  Quantity: ").Append(Quantity).Append("\n");
            sb.Append("  Unit: ").Append(Unit).Append("\n");
            sb.Append("  Price: ").Append(Price).Append("\n");
            sb.Append("  DateOfScanOrModification: ").Append(DateOfScanOrModification).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}


