/*
 * ShopApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = ShopApi.Client.Client.FileParameter;
using OpenAPIDateConverter = ShopApi.Client.Client.OpenAPIDateConverter;
using OpenAPIClientUtils = ShopApi.Client.Client.ClientUtils;

namespace ShopApi.Client.Model
{
    /// <summary>
    /// LoginModel
    /// </summary>
    [DataContract(Name = "LoginModel")]
    public partial class LoginModel : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets LoginType
        /// </summary>
        [DataMember(Name = "loginType", EmitDefaultValue = false)]
        public ELoginType? LoginType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="LoginModel" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected LoginModel() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="LoginModel" /> class.
        /// </summary>
        /// <param name="username">username (required).</param>
        /// <param name="password">password (required).</param>
        /// <param name="ssaid">ssaid.</param>
        /// <param name="loginType">loginType.</param>
        public LoginModel(string username = default(string), string password = default(string), string ssaid = default(string), ELoginType? loginType = default(ELoginType?))
        {
            // to ensure "username" is required (not null)
            if (username == null)
            {
                throw new ArgumentNullException("username is a required property for LoginModel and cannot be null");
            }
            this.Username = username;
            // to ensure "password" is required (not null)
            if (password == null)
            {
                throw new ArgumentNullException("password is a required property for LoginModel and cannot be null");
            }
            this.Password = password;
            this.Ssaid = ssaid;
            this.LoginType = loginType;
        }

        /// <summary>
        /// Gets or Sets Username
        /// </summary>
        [DataMember(Name = "username", IsRequired = true, EmitDefaultValue = true)]
        public string Username { get; set; }

        /// <summary>
        /// Gets or Sets Password
        /// </summary>
        [DataMember(Name = "password", IsRequired = true, EmitDefaultValue = true)]
        public string Password { get; set; }

        /// <summary>
        /// Gets or Sets Ssaid
        /// </summary>
        [DataMember(Name = "ssaid", EmitDefaultValue = true)]
        public string Ssaid { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LoginModel {\n");
            sb.Append("  Username: ").Append(Username).Append("\n");
            sb.Append("  Password: ").Append(Password).Append("\n");
            sb.Append("  Ssaid: ").Append(Ssaid).Append("\n");
            sb.Append("  LoginType: ").Append(LoginType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Username (string) minLength
            if (this.Username != null && this.Username.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Username, length must be greater than 1.", new [] { "Username" });
            }

            // Password (string) minLength
            if (this.Password != null && this.Password.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Password, length must be greater than 1.", new [] { "Password" });
            }

            yield break;
        }
    }

}
