/*
 * ShopApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = ShopApi.Client.Client.FileParameter;
using OpenAPIDateConverter = ShopApi.Client.Client.OpenAPIDateConverter;
using OpenAPIClientUtils = ShopApi.Client.Client.ClientUtils;

namespace ShopApi.Client.Model
{
    /// <summary>
    /// Product
    /// </summary>
    [DataContract(Name = "Product")]
    public partial class Product : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Product" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="name">name.</param>
        /// <param name="brand">brand.</param>
        /// <param name="capacity">capacity.</param>
        /// <param name="label">label.</param>
        /// <param name="isGeneral">isGeneral.</param>
        /// <param name="unitId">unitId.</param>
        /// <param name="unit">unit.</param>
        /// <param name="barcodes">barcodes.</param>
        /// <param name="inventoryPositions">inventoryPositions.</param>
        public Product(int id = default(int), string name = default(string), string brand = default(string), string capacity = default(string), string label = default(string), bool isGeneral = default(bool), int unitId = default(int), Unit unit = default(Unit), Collection<Barcode> barcodes = default(Collection<Barcode>), Collection<InventoryPosition> inventoryPositions = default(Collection<InventoryPosition>))
        {
            this.Id = id;
            this.Name = name;
            this.Brand = brand;
            this.Capacity = capacity;
            this.Label = label;
            this.IsGeneral = isGeneral;
            this.UnitId = unitId;
            this.Unit = unit;
            this.Barcodes = barcodes;
            this.InventoryPositions = inventoryPositions;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public int Id { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Brand
        /// </summary>
        [DataMember(Name = "brand", EmitDefaultValue = true)]
        public string Brand { get; set; }

        /// <summary>
        /// Gets or Sets Capacity
        /// </summary>
        [DataMember(Name = "capacity", EmitDefaultValue = true)]
        public string Capacity { get; set; }

        /// <summary>
        /// Gets or Sets Label
        /// </summary>
        [DataMember(Name = "label", EmitDefaultValue = true)]
        public string Label { get; set; }

        /// <summary>
        /// Gets or Sets IsGeneral
        /// </summary>
        [DataMember(Name = "isGeneral", EmitDefaultValue = true)]
        public bool IsGeneral { get; set; }

        /// <summary>
        /// Gets or Sets UnitId
        /// </summary>
        [DataMember(Name = "unitId", EmitDefaultValue = false)]
        public int UnitId { get; set; }

        /// <summary>
        /// Gets or Sets Unit
        /// </summary>
        [DataMember(Name = "unit", EmitDefaultValue = false)]
        public Unit Unit { get; set; }

        /// <summary>
        /// Gets or Sets Barcodes
        /// </summary>
        [DataMember(Name = "barcodes", EmitDefaultValue = true)]
        public Collection<Barcode> Barcodes { get; set; }

        /// <summary>
        /// Gets or Sets InventoryPositions
        /// </summary>
        [DataMember(Name = "inventoryPositions", EmitDefaultValue = true)]
        public Collection<InventoryPosition> InventoryPositions { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Product {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Brand: ").Append(Brand).Append("\n");
            sb.Append("  Capacity: ").Append(Capacity).Append("\n");
            sb.Append("  Label: ").Append(Label).Append("\n");
            sb.Append("  IsGeneral: ").Append(IsGeneral).Append("\n");
            sb.Append("  UnitId: ").Append(UnitId).Append("\n");
            sb.Append("  Unit: ").Append(Unit).Append("\n");
            sb.Append("  Barcodes: ").Append(Barcodes).Append("\n");
            sb.Append("  InventoryPositions: ").Append(InventoryPositions).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
