/*
 * ShopApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure;
using ShopWeb.Domain.Models;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net.Http;
using System.Net.Mime;
using System.Net;
using System;

namespace ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Api
{

        /// <summary>
        /// Represents a collection of functions to interact with the API endpoints
        /// </summary>
        public interface IInventoryApiSync : IApiAccessor
        {
            #region Synchronous Operations
            /// <summary>
            /// 
            /// </summary>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="commonInventoryPosition"> (optional)</param>
            /// <returns>CommonInventoryPosition</returns>
            CommonInventoryPosition ApiInventoryAddCommonInventoryPositionPost(CommonInventoryPosition? commonInventoryPosition = default);
    
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="commonInventoryPosition"> (optional)</param>
            /// <returns>ApiResponse of CommonInventoryPosition</returns>
            ApiResponse<CommonInventoryPosition> ApiInventoryAddCommonInventoryPositionPostWithHttpInfo(CommonInventoryPosition? commonInventoryPosition = default);
            /// <summary>
            /// 
            /// </summary>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="inventoryPosition"> (optional)</param>
            /// <returns>InventoryPosition</returns>
            InventoryPosition ApiInventoryAddInventoryPositionPost(InventoryPosition? inventoryPosition = default);
    
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="inventoryPosition"> (optional)</param>
            /// <returns>ApiResponse of InventoryPosition</returns>
            ApiResponse<InventoryPosition> ApiInventoryAddInventoryPositionPostWithHttpInfo(InventoryPosition? inventoryPosition = default);
            /// <summary>
            /// 
            /// </summary>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="inventory"> (optional)</param>
            /// <returns>int</returns>
            int ApiInventoryCreateInventoryPost(Inventory? inventory = default);
    
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="inventory"> (optional)</param>
            /// <returns>ApiResponse of int</returns>
            ApiResponse<int> ApiInventoryCreateInventoryPostWithHttpInfo(Inventory? inventory = default);
            /// <summary>
            /// 
            /// </summary>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="commonInventoryPosition"> (optional)</param>
            /// <returns>int</returns>
            int ApiInventoryDeleteCommonInventoryPositionPost(CommonInventoryPosition? commonInventoryPosition = default);
    
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="commonInventoryPosition"> (optional)</param>
            /// <returns>ApiResponse of int</returns>
            ApiResponse<int> ApiInventoryDeleteCommonInventoryPositionPostWithHttpInfo(CommonInventoryPosition? commonInventoryPosition = default);
            /// <summary>
            /// 
            /// </summary>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="inventoryPosition"> (optional)</param>
            /// <returns>int</returns>
            int ApiInventoryDeleteInventoryPositionPost(InventoryPosition? inventoryPosition = default);
    
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="inventoryPosition"> (optional)</param>
            /// <returns>ApiResponse of int</returns>
            ApiResponse<int> ApiInventoryDeleteInventoryPositionPostWithHttpInfo(InventoryPosition? inventoryPosition = default);
            /// <summary>
            /// 
            /// </summary>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="commonInventoryPosition"> (optional)</param>
            /// <returns>CommonInventoryPosition</returns>
            CommonInventoryPosition ApiInventoryEditCommonInventoryPositionPost(CommonInventoryPosition? commonInventoryPosition = default);
    
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="commonInventoryPosition"> (optional)</param>
            /// <returns>ApiResponse of CommonInventoryPosition</returns>
            ApiResponse<CommonInventoryPosition> ApiInventoryEditCommonInventoryPositionPostWithHttpInfo(CommonInventoryPosition? commonInventoryPosition = default);
            /// <summary>
            /// 
            /// </summary>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="inventoryPosition"> (optional)</param>
            /// <returns>InventoryPosition</returns>
            InventoryPosition ApiInventoryEditInventoryPositionPost(InventoryPosition? inventoryPosition = default);
    
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="inventoryPosition"> (optional)</param>
            /// <returns>ApiResponse of InventoryPosition</returns>
            ApiResponse<InventoryPosition> ApiInventoryEditInventoryPositionPostWithHttpInfo(InventoryPosition? inventoryPosition = default);
            /// <summary>
            /// 
            /// </summary>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="inventoryId"> (optional)</param>
            /// <param name="userId"> (optional)</param>
            /// <returns>List&lt;CommonInventoryPosition&gt;</returns>
            List<CommonInventoryPosition> ApiInventoryGetAllCommonInventoryPositionsForUserGet(int? inventoryId = default, int? userId = default);
    
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="inventoryId"> (optional)</param>
            /// <param name="userId"> (optional)</param>
            /// <returns>ApiResponse of List&lt;CommonInventoryPosition&gt;</returns>
            ApiResponse<List<CommonInventoryPosition>> ApiInventoryGetAllCommonInventoryPositionsForUserGetWithHttpInfo(int? inventoryId = default, int? userId = default);
            /// <summary>
            /// 
            /// </summary>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="inventoryId"> (optional)</param>
            /// <returns>List&lt;CommonInventoryPosition&gt;</returns>
            List<CommonInventoryPosition> ApiInventoryGetAllCommonInventoryPositionsGet(int? inventoryId = default);
    
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="inventoryId"> (optional)</param>
            /// <returns>ApiResponse of List&lt;CommonInventoryPosition&gt;</returns>
            ApiResponse<List<CommonInventoryPosition>> ApiInventoryGetAllCommonInventoryPositionsGetWithHttpInfo(int? inventoryId = default);
            /// <summary>
            /// 
            /// </summary>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <returns>List&lt;Inventory&gt;</returns>
            List<Inventory> ApiInventoryGetAllInventoriesGet();
    
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <returns>ApiResponse of List&lt;Inventory&gt;</returns>
            ApiResponse<List<Inventory>> ApiInventoryGetAllInventoriesGetWithHttpInfo();
            /// <summary>
            /// 
            /// </summary>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="inventoryId"> (optional)</param>
            /// <param name="userId"> (optional)</param>
            /// <returns>List&lt;InventoryPosition&gt;</returns>
            List<InventoryPosition> ApiInventoryGetAllInventoryPositionsForUserGet(int? inventoryId = default, int? userId = default);
    
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="inventoryId"> (optional)</param>
            /// <param name="userId"> (optional)</param>
            /// <returns>ApiResponse of List&lt;InventoryPosition&gt;</returns>
            ApiResponse<List<InventoryPosition>> ApiInventoryGetAllInventoryPositionsForUserGetWithHttpInfo(int? inventoryId = default, int? userId = default);
            /// <summary>
            /// 
            /// </summary>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="inventoryId"> (optional)</param>
            /// <returns>List&lt;InventoryPosition&gt;</returns>
            List<InventoryPosition> ApiInventoryGetAllInventoryPositionsGet(int? inventoryId = default);
    
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="inventoryId"> (optional)</param>
            /// <returns>ApiResponse of List&lt;InventoryPosition&gt;</returns>
            ApiResponse<List<InventoryPosition>> ApiInventoryGetAllInventoryPositionsGetWithHttpInfo(int? inventoryId = default);
            /// <summary>
            /// 
            /// </summary>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="inventoryId"> (optional)</param>
            /// <returns>Inventory</returns>
            Inventory ApiInventoryGetInventoryByIdGet(int? inventoryId = default);
    
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="inventoryId"> (optional)</param>
            /// <returns>ApiResponse of Inventory</returns>
            ApiResponse<Inventory> ApiInventoryGetInventoryByIdGetWithHttpInfo(int? inventoryId = default);
            #endregion Synchronous Operations
        }

        /// <summary>
        /// Represents a collection of functions to interact with the API endpoints
        /// </summary>
        public interface IInventoryApiAsync : IApiAccessor
        {
            #region Asynchronous Operations
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="commonInventoryPosition"> (optional)</param>
            /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
            /// <returns>Task of CommonInventoryPosition</returns>
            System.Threading.Tasks.Task<CommonInventoryPosition> ApiInventoryAddCommonInventoryPositionPostAsync(CommonInventoryPosition? commonInventoryPosition = default, System.Threading.CancellationToken cancellationToken = default);
    
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="commonInventoryPosition"> (optional)</param>
            /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
            /// <returns>Task of ApiResponse (CommonInventoryPosition)</returns>
            System.Threading.Tasks.Task<ApiResponse<CommonInventoryPosition>> ApiInventoryAddCommonInventoryPositionPostWithHttpInfoAsync(CommonInventoryPosition? commonInventoryPosition = default, System.Threading.CancellationToken cancellationToken = default);
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="inventoryPosition"> (optional)</param>
            /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
            /// <returns>Task of InventoryPosition</returns>
            System.Threading.Tasks.Task<InventoryPosition> ApiInventoryAddInventoryPositionPostAsync(InventoryPosition? inventoryPosition = default, System.Threading.CancellationToken cancellationToken = default);
    
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="inventoryPosition"> (optional)</param>
            /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
            /// <returns>Task of ApiResponse (InventoryPosition)</returns>
            System.Threading.Tasks.Task<ApiResponse<InventoryPosition>> ApiInventoryAddInventoryPositionPostWithHttpInfoAsync(InventoryPosition? inventoryPosition = default, System.Threading.CancellationToken cancellationToken = default);
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="inventory"> (optional)</param>
            /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
            /// <returns>Task of int</returns>
            System.Threading.Tasks.Task<int> ApiInventoryCreateInventoryPostAsync(Inventory? inventory = default, System.Threading.CancellationToken cancellationToken = default);
    
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="inventory"> (optional)</param>
            /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
            /// <returns>Task of ApiResponse (int)</returns>
            System.Threading.Tasks.Task<ApiResponse<int>> ApiInventoryCreateInventoryPostWithHttpInfoAsync(Inventory? inventory = default, System.Threading.CancellationToken cancellationToken = default);
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="commonInventoryPosition"> (optional)</param>
            /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
            /// <returns>Task of int</returns>
            System.Threading.Tasks.Task<int> ApiInventoryDeleteCommonInventoryPositionPostAsync(CommonInventoryPosition? commonInventoryPosition = default, System.Threading.CancellationToken cancellationToken = default);
    
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="commonInventoryPosition"> (optional)</param>
            /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
            /// <returns>Task of ApiResponse (int)</returns>
            System.Threading.Tasks.Task<ApiResponse<int>> ApiInventoryDeleteCommonInventoryPositionPostWithHttpInfoAsync(CommonInventoryPosition? commonInventoryPosition = default, System.Threading.CancellationToken cancellationToken = default);
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="inventoryPosition"> (optional)</param>
            /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
            /// <returns>Task of int</returns>
            System.Threading.Tasks.Task<int> ApiInventoryDeleteInventoryPositionPostAsync(InventoryPosition? inventoryPosition = default, System.Threading.CancellationToken cancellationToken = default);
    
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="inventoryPosition"> (optional)</param>
            /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
            /// <returns>Task of ApiResponse (int)</returns>
            System.Threading.Tasks.Task<ApiResponse<int>> ApiInventoryDeleteInventoryPositionPostWithHttpInfoAsync(InventoryPosition? inventoryPosition = default, System.Threading.CancellationToken cancellationToken = default);
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="commonInventoryPosition"> (optional)</param>
            /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
            /// <returns>Task of CommonInventoryPosition</returns>
            System.Threading.Tasks.Task<CommonInventoryPosition> ApiInventoryEditCommonInventoryPositionPostAsync(CommonInventoryPosition? commonInventoryPosition = default, System.Threading.CancellationToken cancellationToken = default);
    
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="commonInventoryPosition"> (optional)</param>
            /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
            /// <returns>Task of ApiResponse (CommonInventoryPosition)</returns>
            System.Threading.Tasks.Task<ApiResponse<CommonInventoryPosition>> ApiInventoryEditCommonInventoryPositionPostWithHttpInfoAsync(CommonInventoryPosition? commonInventoryPosition = default, System.Threading.CancellationToken cancellationToken = default);
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="inventoryPosition"> (optional)</param>
            /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
            /// <returns>Task of InventoryPosition</returns>
            System.Threading.Tasks.Task<InventoryPosition> ApiInventoryEditInventoryPositionPostAsync(InventoryPosition? inventoryPosition = default, System.Threading.CancellationToken cancellationToken = default);
    
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="inventoryPosition"> (optional)</param>
            /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
            /// <returns>Task of ApiResponse (InventoryPosition)</returns>
            System.Threading.Tasks.Task<ApiResponse<InventoryPosition>> ApiInventoryEditInventoryPositionPostWithHttpInfoAsync(InventoryPosition? inventoryPosition = default, System.Threading.CancellationToken cancellationToken = default);
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="inventoryId"> (optional)</param>
            /// <param name="userId"> (optional)</param>
            /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
            /// <returns>Task of List&lt;CommonInventoryPosition&gt;</returns>
            System.Threading.Tasks.Task<List<CommonInventoryPosition>> ApiInventoryGetAllCommonInventoryPositionsForUserGetAsync(int? inventoryId = default, int? userId = default, System.Threading.CancellationToken cancellationToken = default);
    
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="inventoryId"> (optional)</param>
            /// <param name="userId"> (optional)</param>
            /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
            /// <returns>Task of ApiResponse (List&lt;CommonInventoryPosition&gt;)</returns>
            System.Threading.Tasks.Task<ApiResponse<List<CommonInventoryPosition>>> ApiInventoryGetAllCommonInventoryPositionsForUserGetWithHttpInfoAsync(int? inventoryId = default, int? userId = default, System.Threading.CancellationToken cancellationToken = default);
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="inventoryId"> (optional)</param>
            /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
            /// <returns>Task of List&lt;CommonInventoryPosition&gt;</returns>
            System.Threading.Tasks.Task<List<CommonInventoryPosition>> ApiInventoryGetAllCommonInventoryPositionsGetAsync(int? inventoryId = default, System.Threading.CancellationToken cancellationToken = default);
    
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="inventoryId"> (optional)</param>
            /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
            /// <returns>Task of ApiResponse (List&lt;CommonInventoryPosition&gt;)</returns>
            System.Threading.Tasks.Task<ApiResponse<List<CommonInventoryPosition>>> ApiInventoryGetAllCommonInventoryPositionsGetWithHttpInfoAsync(int? inventoryId = default, System.Threading.CancellationToken cancellationToken = default);
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
            /// <returns>Task of List&lt;Inventory&gt;</returns>
            System.Threading.Tasks.Task<List<Inventory>> ApiInventoryGetAllInventoriesGetAsync(System.Threading.CancellationToken cancellationToken = default);
    
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
            /// <returns>Task of ApiResponse (List&lt;Inventory&gt;)</returns>
            System.Threading.Tasks.Task<ApiResponse<List<Inventory>>> ApiInventoryGetAllInventoriesGetWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default);
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="inventoryId"> (optional)</param>
            /// <param name="userId"> (optional)</param>
            /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
            /// <returns>Task of List&lt;InventoryPosition&gt;</returns>
            System.Threading.Tasks.Task<List<InventoryPosition>> ApiInventoryGetAllInventoryPositionsForUserGetAsync(int? inventoryId = default, int? userId = default, System.Threading.CancellationToken cancellationToken = default);
    
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="inventoryId"> (optional)</param>
            /// <param name="userId"> (optional)</param>
            /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
            /// <returns>Task of ApiResponse (List&lt;InventoryPosition&gt;)</returns>
            System.Threading.Tasks.Task<ApiResponse<List<InventoryPosition>>> ApiInventoryGetAllInventoryPositionsForUserGetWithHttpInfoAsync(int? inventoryId = default, int? userId = default, System.Threading.CancellationToken cancellationToken = default);
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="inventoryId"> (optional)</param>
            /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
            /// <returns>Task of List&lt;InventoryPosition&gt;</returns>
            System.Threading.Tasks.Task<List<InventoryPosition>> ApiInventoryGetAllInventoryPositionsGetAsync(int? inventoryId = default, System.Threading.CancellationToken cancellationToken = default);
    
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="inventoryId"> (optional)</param>
            /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
            /// <returns>Task of ApiResponse (List&lt;InventoryPosition&gt;)</returns>
            System.Threading.Tasks.Task<ApiResponse<List<InventoryPosition>>> ApiInventoryGetAllInventoryPositionsGetWithHttpInfoAsync(int? inventoryId = default, System.Threading.CancellationToken cancellationToken = default);
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="inventoryId"> (optional)</param>
            /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
            /// <returns>Task of Inventory</returns>
            System.Threading.Tasks.Task<Inventory> ApiInventoryGetInventoryByIdGetAsync(int? inventoryId = default, System.Threading.CancellationToken cancellationToken = default);
    
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="inventoryId"> (optional)</param>
            /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
            /// <returns>Task of ApiResponse (Inventory)</returns>
            System.Threading.Tasks.Task<ApiResponse<Inventory>> ApiInventoryGetInventoryByIdGetWithHttpInfoAsync(int? inventoryId = default, System.Threading.CancellationToken cancellationToken = default);
            #endregion Asynchronous Operations
        }

        /// <summary>
        /// Represents a collection of functions to interact with the API endpoints
        /// </summary>
        public interface IInventoryApi : IInventoryApiSync, IInventoryApiAsync
        {
    
        }
}

