/*
 * ShopApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure;
using ShopWeb.Domain.Models;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net.Http;
using System.Net.Mime;
using System.Net;
using System;

namespace ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Api
{

        /// <summary>
        /// Represents a collection of functions to interact with the API endpoints
        /// </summary>
        public interface IInventoryApiSync : IApiAccessor
        {
            #region Synchronous Operations
            /// <summary>
            /// 
            /// </summary>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="commonInventoryPosition"> (optional)</param>
            /// <returns>int</returns>
            int ApiInventoryAddCommonInventoryPositionPost(CommonInventoryPosition? commonInventoryPosition = default);
    
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="commonInventoryPosition"> (optional)</param>
            /// <returns>ApiResponse of int</returns>
            ApiResponse<int> ApiInventoryAddCommonInventoryPositionPostWithHttpInfo(CommonInventoryPosition? commonInventoryPosition = default);
            /// <summary>
            /// 
            /// </summary>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="inventoryPosition"> (optional)</param>
            /// <returns>int</returns>
            int ApiInventoryAddInventoryPositionPost(InventoryPosition? inventoryPosition = default);
    
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="inventoryPosition"> (optional)</param>
            /// <returns>ApiResponse of int</returns>
            ApiResponse<int> ApiInventoryAddInventoryPositionPostWithHttpInfo(InventoryPosition? inventoryPosition = default);
            /// <summary>
            /// 
            /// </summary>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="inventory"> (optional)</param>
            /// <returns>int</returns>
            int ApiInventoryCreateInventoryPost(Inventory? inventory = default);
    
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="inventory"> (optional)</param>
            /// <returns>ApiResponse of int</returns>
            ApiResponse<int> ApiInventoryCreateInventoryPostWithHttpInfo(Inventory? inventory = default);
            /// <summary>
            /// 
            /// </summary>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="commonInventoryPosition"> (optional)</param>
            /// <returns>int</returns>
            int ApiInventoryEditCommonInventoryPositionPost(CommonInventoryPosition? commonInventoryPosition = default);
    
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="commonInventoryPosition"> (optional)</param>
            /// <returns>ApiResponse of int</returns>
            ApiResponse<int> ApiInventoryEditCommonInventoryPositionPostWithHttpInfo(CommonInventoryPosition? commonInventoryPosition = default);
            /// <summary>
            /// 
            /// </summary>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="inventoryPosition"> (optional)</param>
            /// <returns>int</returns>
            int ApiInventoryEditInventoryPositionPost(InventoryPosition? inventoryPosition = default);
    
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="inventoryPosition"> (optional)</param>
            /// <returns>ApiResponse of int</returns>
            ApiResponse<int> ApiInventoryEditInventoryPositionPostWithHttpInfo(InventoryPosition? inventoryPosition = default);
            /// <summary>
            /// 
            /// </summary>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <returns>List&lt;Inventory&gt;</returns>
            List<Inventory> ApiInventoryGetAllInventoriesGet();
    
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <returns>ApiResponse of List&lt;Inventory&gt;</returns>
            ApiResponse<List<Inventory>> ApiInventoryGetAllInventoriesGetWithHttpInfo();
            /// <summary>
            /// 
            /// </summary>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="inventoryId"> (optional)</param>
            /// <param name="userId"> (optional)</param>
            /// <returns>List&lt;Inventory&gt;</returns>
            List<Inventory> ApiInventoryGetAllInventoryPositionsForUserGet(int? inventoryId = default, int? userId = default);
    
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="inventoryId"> (optional)</param>
            /// <param name="userId"> (optional)</param>
            /// <returns>ApiResponse of List&lt;Inventory&gt;</returns>
            ApiResponse<List<Inventory>> ApiInventoryGetAllInventoryPositionsForUserGetWithHttpInfo(int? inventoryId = default, int? userId = default);
            /// <summary>
            /// 
            /// </summary>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="inventoryId"> (optional)</param>
            /// <returns>List&lt;Inventory&gt;</returns>
            List<Inventory> ApiInventoryGetAllInventoryPositionsGet(int? inventoryId = default);
    
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="inventoryId"> (optional)</param>
            /// <returns>ApiResponse of List&lt;Inventory&gt;</returns>
            ApiResponse<List<Inventory>> ApiInventoryGetAllInventoryPositionsGetWithHttpInfo(int? inventoryId = default);
            /// <summary>
            /// 
            /// </summary>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="inventoryId"> (optional)</param>
            /// <returns>Inventory</returns>
            Inventory ApiInventoryGetInventoryByIdGet(int? inventoryId = default);
    
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="inventoryId"> (optional)</param>
            /// <returns>ApiResponse of Inventory</returns>
            ApiResponse<Inventory> ApiInventoryGetInventoryByIdGetWithHttpInfo(int? inventoryId = default);
            #endregion Synchronous Operations
        }

        /// <summary>
        /// Represents a collection of functions to interact with the API endpoints
        /// </summary>
        public interface IInventoryApiAsync : IApiAccessor
        {
            #region Asynchronous Operations
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="commonInventoryPosition"> (optional)</param>
            /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
            /// <returns>Task of int</returns>
            System.Threading.Tasks.Task<int> ApiInventoryAddCommonInventoryPositionPostAsync(CommonInventoryPosition? commonInventoryPosition = default, System.Threading.CancellationToken cancellationToken = default);
    
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="commonInventoryPosition"> (optional)</param>
            /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
            /// <returns>Task of ApiResponse (int)</returns>
            System.Threading.Tasks.Task<ApiResponse<int>> ApiInventoryAddCommonInventoryPositionPostWithHttpInfoAsync(CommonInventoryPosition? commonInventoryPosition = default, System.Threading.CancellationToken cancellationToken = default);
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="inventoryPosition"> (optional)</param>
            /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
            /// <returns>Task of int</returns>
            System.Threading.Tasks.Task<int> ApiInventoryAddInventoryPositionPostAsync(InventoryPosition? inventoryPosition = default, System.Threading.CancellationToken cancellationToken = default);
    
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="inventoryPosition"> (optional)</param>
            /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
            /// <returns>Task of ApiResponse (int)</returns>
            System.Threading.Tasks.Task<ApiResponse<int>> ApiInventoryAddInventoryPositionPostWithHttpInfoAsync(InventoryPosition? inventoryPosition = default, System.Threading.CancellationToken cancellationToken = default);
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="inventory"> (optional)</param>
            /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
            /// <returns>Task of int</returns>
            System.Threading.Tasks.Task<int> ApiInventoryCreateInventoryPostAsync(Inventory? inventory = default, System.Threading.CancellationToken cancellationToken = default);
    
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="inventory"> (optional)</param>
            /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
            /// <returns>Task of ApiResponse (int)</returns>
            System.Threading.Tasks.Task<ApiResponse<int>> ApiInventoryCreateInventoryPostWithHttpInfoAsync(Inventory? inventory = default, System.Threading.CancellationToken cancellationToken = default);
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="commonInventoryPosition"> (optional)</param>
            /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
            /// <returns>Task of int</returns>
            System.Threading.Tasks.Task<int> ApiInventoryEditCommonInventoryPositionPostAsync(CommonInventoryPosition? commonInventoryPosition = default, System.Threading.CancellationToken cancellationToken = default);
    
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="commonInventoryPosition"> (optional)</param>
            /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
            /// <returns>Task of ApiResponse (int)</returns>
            System.Threading.Tasks.Task<ApiResponse<int>> ApiInventoryEditCommonInventoryPositionPostWithHttpInfoAsync(CommonInventoryPosition? commonInventoryPosition = default, System.Threading.CancellationToken cancellationToken = default);
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="inventoryPosition"> (optional)</param>
            /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
            /// <returns>Task of int</returns>
            System.Threading.Tasks.Task<int> ApiInventoryEditInventoryPositionPostAsync(InventoryPosition? inventoryPosition = default, System.Threading.CancellationToken cancellationToken = default);
    
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="inventoryPosition"> (optional)</param>
            /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
            /// <returns>Task of ApiResponse (int)</returns>
            System.Threading.Tasks.Task<ApiResponse<int>> ApiInventoryEditInventoryPositionPostWithHttpInfoAsync(InventoryPosition? inventoryPosition = default, System.Threading.CancellationToken cancellationToken = default);
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
            /// <returns>Task of List&lt;Inventory&gt;</returns>
            System.Threading.Tasks.Task<List<Inventory>> ApiInventoryGetAllInventoriesGetAsync(System.Threading.CancellationToken cancellationToken = default);
    
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
            /// <returns>Task of ApiResponse (List&lt;Inventory&gt;)</returns>
            System.Threading.Tasks.Task<ApiResponse<List<Inventory>>> ApiInventoryGetAllInventoriesGetWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default);
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="inventoryId"> (optional)</param>
            /// <param name="userId"> (optional)</param>
            /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
            /// <returns>Task of List&lt;Inventory&gt;</returns>
            System.Threading.Tasks.Task<List<Inventory>> ApiInventoryGetAllInventoryPositionsForUserGetAsync(int? inventoryId = default, int? userId = default, System.Threading.CancellationToken cancellationToken = default);
    
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="inventoryId"> (optional)</param>
            /// <param name="userId"> (optional)</param>
            /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
            /// <returns>Task of ApiResponse (List&lt;Inventory&gt;)</returns>
            System.Threading.Tasks.Task<ApiResponse<List<Inventory>>> ApiInventoryGetAllInventoryPositionsForUserGetWithHttpInfoAsync(int? inventoryId = default, int? userId = default, System.Threading.CancellationToken cancellationToken = default);
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="inventoryId"> (optional)</param>
            /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
            /// <returns>Task of List&lt;Inventory&gt;</returns>
            System.Threading.Tasks.Task<List<Inventory>> ApiInventoryGetAllInventoryPositionsGetAsync(int? inventoryId = default, System.Threading.CancellationToken cancellationToken = default);
    
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="inventoryId"> (optional)</param>
            /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
            /// <returns>Task of ApiResponse (List&lt;Inventory&gt;)</returns>
            System.Threading.Tasks.Task<ApiResponse<List<Inventory>>> ApiInventoryGetAllInventoryPositionsGetWithHttpInfoAsync(int? inventoryId = default, System.Threading.CancellationToken cancellationToken = default);
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="inventoryId"> (optional)</param>
            /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
            /// <returns>Task of Inventory</returns>
            System.Threading.Tasks.Task<Inventory> ApiInventoryGetInventoryByIdGetAsync(int? inventoryId = default, System.Threading.CancellationToken cancellationToken = default);
    
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="inventoryId"> (optional)</param>
            /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
            /// <returns>Task of ApiResponse (Inventory)</returns>
            System.Threading.Tasks.Task<ApiResponse<Inventory>> ApiInventoryGetInventoryByIdGetWithHttpInfoAsync(int? inventoryId = default, System.Threading.CancellationToken cancellationToken = default);
            #endregion Asynchronous Operations
        }

        /// <summary>
        /// Represents a collection of functions to interact with the API endpoints
        /// </summary>
        public interface IInventoryApi : IInventoryApiSync, IInventoryApiAsync
        {
    
        }
}

