/*
 * ShopApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure;
using ShopWeb.Domain.Models;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net.Http;
using System.Net.Mime;
using System.Net;
using System;

namespace ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Api
{

        /// <summary>
        /// Represents a collection of functions to interact with the API endpoints
        /// </summary>
        public interface IInventoryApiSync : IApiAccessor
        {
            #region Synchronous Operations
            /// <summary>
            /// 
            /// </summary>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <returns>List&lt;Inventory&gt;</returns>
            List<Inventory> ApiInventoryGetAllInventoriesGet();
    
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <returns>ApiResponse of List&lt;Inventory&gt;</returns>
            ApiResponse<List<Inventory>> ApiInventoryGetAllInventoriesGetWithHttpInfo();
            /// <summary>
            /// 
            /// </summary>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="inventoryId"> (optional)</param>
            /// <returns>Inventory</returns>
            Inventory ApiInventoryGetInventoryByIdGet(int? inventoryId = default);
    
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="inventoryId"> (optional)</param>
            /// <returns>ApiResponse of Inventory</returns>
            ApiResponse<Inventory> ApiInventoryGetInventoryByIdGetWithHttpInfo(int? inventoryId = default);
            #endregion Synchronous Operations
        }

        /// <summary>
        /// Represents a collection of functions to interact with the API endpoints
        /// </summary>
        public interface IInventoryApiAsync : IApiAccessor
        {
            #region Asynchronous Operations
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
            /// <returns>Task of List&lt;Inventory&gt;</returns>
            System.Threading.Tasks.Task<List<Inventory>> ApiInventoryGetAllInventoriesGetAsync(System.Threading.CancellationToken cancellationToken = default);
    
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
            /// <returns>Task of ApiResponse (List&lt;Inventory&gt;)</returns>
            System.Threading.Tasks.Task<ApiResponse<List<Inventory>>> ApiInventoryGetAllInventoriesGetWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default);
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="inventoryId"> (optional)</param>
            /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
            /// <returns>Task of Inventory</returns>
            System.Threading.Tasks.Task<Inventory> ApiInventoryGetInventoryByIdGetAsync(int? inventoryId = default, System.Threading.CancellationToken cancellationToken = default);
    
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="inventoryId"> (optional)</param>
            /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
            /// <returns>Task of ApiResponse (Inventory)</returns>
            System.Threading.Tasks.Task<ApiResponse<Inventory>> ApiInventoryGetInventoryByIdGetWithHttpInfoAsync(int? inventoryId = default, System.Threading.CancellationToken cancellationToken = default);
            #endregion Asynchronous Operations
        }

        /// <summary>
        /// Represents a collection of functions to interact with the API endpoints
        /// </summary>
        public interface IInventoryApi : IInventoryApiSync, IInventoryApiAsync
        {
    
        }
}

