/*
 * ShopApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure;
using ShopWeb.Domain.Models;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net.Http;
using System.Net.Mime;
using System.Net;
using System;

namespace ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Api
{

        /// <summary>
        /// Represents a collection of functions to interact with the API endpoints
        /// </summary>
        public interface IProductApiSync : IApiAccessor
        {
            #region Synchronous Operations
            /// <summary>
            /// 
            /// </summary>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="product"> (optional)</param>
            /// <returns></returns>
            void ApiProductAddProductPost(Product? product = default);
    
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="product"> (optional)</param>
            /// <returns>ApiResponse of Object(void)</returns>
            ApiResponse<Object> ApiProductAddProductPostWithHttpInfo(Product? product = default);
            /// <summary>
            /// 
            /// </summary>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <returns></returns>
            void ApiProductGetAllProductsGet();
    
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <returns>ApiResponse of Object(void)</returns>
            ApiResponse<Object> ApiProductGetAllProductsGetWithHttpInfo();
            /// <summary>
            /// 
            /// </summary>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <returns></returns>
            void ApiProductGetAllProductsTestOpenApiGenerateGet();
    
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <returns>ApiResponse of Object(void)</returns>
            ApiResponse<Object> ApiProductGetAllProductsTestOpenApiGenerateGetWithHttpInfo();
            /// <summary>
            /// 
            /// </summary>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="barcode"> (optional)</param>
            /// <returns>List&lt;Product&gt;</returns>
            List<Product> ApiProductGetProductByBarcodeGet(string? barcode = default);
    
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="barcode"> (optional)</param>
            /// <returns>ApiResponse of List&lt;Product&gt;</returns>
            ApiResponse<List<Product>> ApiProductGetProductByBarcodeGetWithHttpInfo(string? barcode = default);
            /// <summary>
            /// 
            /// </summary>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="barcode"> (optional)</param>
            /// <returns>Product</returns>
            Product ApiProductGetProductFromOpenFoodFactsGet(string? barcode = default);
    
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="barcode"> (optional)</param>
            /// <returns>ApiResponse of Product</returns>
            ApiResponse<Product> ApiProductGetProductFromOpenFoodFactsGetWithHttpInfo(string? barcode = default);
            /// <summary>
            /// 
            /// </summary>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <returns></returns>
            void ApiProductInitProductFromCSVPost();
    
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <returns>ApiResponse of Object(void)</returns>
            ApiResponse<Object> ApiProductInitProductFromCSVPostWithHttpInfo();
            /// <summary>
            /// 
            /// </summary>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <returns></returns>
            void ApiProductTestApiDirectlyGet();
    
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <returns>ApiResponse of Object(void)</returns>
            ApiResponse<Object> ApiProductTestApiDirectlyGetWithHttpInfo();
            #endregion Synchronous Operations
        }

        /// <summary>
        /// Represents a collection of functions to interact with the API endpoints
        /// </summary>
        public interface IProductApiAsync : IApiAccessor
        {
            #region Asynchronous Operations
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="product"> (optional)</param>
            /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
            /// <returns>Task of void</returns>
            System.Threading.Tasks.Task ApiProductAddProductPostAsync(Product? product = default, System.Threading.CancellationToken cancellationToken = default);
    
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="product"> (optional)</param>
            /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
            /// <returns>Task of ApiResponse</returns>
            System.Threading.Tasks.Task<ApiResponse<Object>> ApiProductAddProductPostWithHttpInfoAsync(Product? product = default, System.Threading.CancellationToken cancellationToken = default);
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
            /// <returns>Task of void</returns>
            System.Threading.Tasks.Task ApiProductGetAllProductsGetAsync(System.Threading.CancellationToken cancellationToken = default);
    
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
            /// <returns>Task of ApiResponse</returns>
            System.Threading.Tasks.Task<ApiResponse<Object>> ApiProductGetAllProductsGetWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default);
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
            /// <returns>Task of void</returns>
            System.Threading.Tasks.Task ApiProductGetAllProductsTestOpenApiGenerateGetAsync(System.Threading.CancellationToken cancellationToken = default);
    
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
            /// <returns>Task of ApiResponse</returns>
            System.Threading.Tasks.Task<ApiResponse<Object>> ApiProductGetAllProductsTestOpenApiGenerateGetWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default);
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="barcode"> (optional)</param>
            /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
            /// <returns>Task of List&lt;Product&gt;</returns>
            System.Threading.Tasks.Task<List<Product>> ApiProductGetProductByBarcodeGetAsync(string? barcode = default, System.Threading.CancellationToken cancellationToken = default);
    
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="barcode"> (optional)</param>
            /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
            /// <returns>Task of ApiResponse (List&lt;Product&gt;)</returns>
            System.Threading.Tasks.Task<ApiResponse<List<Product>>> ApiProductGetProductByBarcodeGetWithHttpInfoAsync(string? barcode = default, System.Threading.CancellationToken cancellationToken = default);
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="barcode"> (optional)</param>
            /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
            /// <returns>Task of Product</returns>
            System.Threading.Tasks.Task<Product> ApiProductGetProductFromOpenFoodFactsGetAsync(string? barcode = default, System.Threading.CancellationToken cancellationToken = default);
    
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="barcode"> (optional)</param>
            /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
            /// <returns>Task of ApiResponse (Product)</returns>
            System.Threading.Tasks.Task<ApiResponse<Product>> ApiProductGetProductFromOpenFoodFactsGetWithHttpInfoAsync(string? barcode = default, System.Threading.CancellationToken cancellationToken = default);
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
            /// <returns>Task of void</returns>
            System.Threading.Tasks.Task ApiProductInitProductFromCSVPostAsync(System.Threading.CancellationToken cancellationToken = default);
    
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
            /// <returns>Task of ApiResponse</returns>
            System.Threading.Tasks.Task<ApiResponse<Object>> ApiProductInitProductFromCSVPostWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default);
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
            /// <returns>Task of void</returns>
            System.Threading.Tasks.Task ApiProductTestApiDirectlyGetAsync(System.Threading.CancellationToken cancellationToken = default);
    
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
            /// <returns>Task of ApiResponse</returns>
            System.Threading.Tasks.Task<ApiResponse<Object>> ApiProductTestApiDirectlyGetWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default);
            #endregion Asynchronous Operations
        }

        /// <summary>
        /// Represents a collection of functions to interact with the API endpoints
        /// </summary>
        public interface IProductApi : IProductApiSync, IProductApiAsync
        {
    
        }
}

