/*
 * ShopApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure;
using ShopWeb.Domain.Models;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net.Http;
using System.Net.Mime;
using System.Net;
using System;

namespace ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Api
{

        /// <summary>
        /// Represents a collection of functions to interact with the API endpoints
        /// </summary>
        public interface IUserApiSync : IApiAccessor
        {
            #region Synchronous Operations
            /// <summary>
            /// 
            /// </summary>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="idUser"> (optional)</param>
            /// <returns>UserInfo</returns>
            UserInfo ApiUserGetUserGet(int? idUser = default);
    
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="idUser"> (optional)</param>
            /// <returns>ApiResponse of UserInfo</returns>
            ApiResponse<UserInfo> ApiUserGetUserGetWithHttpInfo(int? idUser = default);
            #endregion Synchronous Operations
        }

        /// <summary>
        /// Represents a collection of functions to interact with the API endpoints
        /// </summary>
        public interface IUserApiAsync : IApiAccessor
        {
            #region Asynchronous Operations
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="idUser"> (optional)</param>
            /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
            /// <returns>Task of UserInfo</returns>
            System.Threading.Tasks.Task<UserInfo> ApiUserGetUserGetAsync(int? idUser = default, System.Threading.CancellationToken cancellationToken = default);
    
            /// <summary>
            /// 
            /// </summary>
            /// <remarks>
            /// 
            /// </remarks>
            /// <exception cref="ShopWeb.Infrastructure.ApiClient.OpenApiGenerate.Infrastructure.ApiException">Thrown when fails to make API call</exception>
            /// <param name="idUser"> (optional)</param>
            /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
            /// <returns>Task of ApiResponse (UserInfo)</returns>
            System.Threading.Tasks.Task<ApiResponse<UserInfo>> ApiUserGetUserGetWithHttpInfoAsync(int? idUser = default, System.Threading.CancellationToken cancellationToken = default);
            #endregion Asynchronous Operations
        }

        /// <summary>
        /// Represents a collection of functions to interact with the API endpoints
        /// </summary>
        public interface IUserApi : IUserApiSync, IUserApiAsync
        {
    
        }
}

