/*
 * ShopApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using ShopApi.Client.Client;
using ShopApi.Client.Api;
// uncomment below to import models
//using ShopApi.Client.Model;

namespace ShopApi.Client.Test.Api
{
    /// <summary>
    ///  Class for testing LoginApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class LoginApiTests : IDisposable
    {
        private LoginApi instance;

        public LoginApiTests()
        {
            instance = new LoginApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LoginApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' LoginApi
            //Assert.IsType<LoginApi>(instance);
        }

        /// <summary>
        /// Test ApiLoginLoginPost
        /// </summary>
        [Fact]
        public void ApiLoginLoginPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //LoginModel? loginModel = null;
            //var response = instance.ApiLoginLoginPost(loginModel);
            //Assert.IsType<string>(response);
        }

        /// <summary>
        /// Test ApiLoginLogoutPost
        /// </summary>
        [Fact]
        public void ApiLoginLogoutPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.ApiLoginLogoutPost();
        }

        /// <summary>
        /// Test ApiLoginRefreshPost
        /// </summary>
        [Fact]
        public void ApiLoginRefreshPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string? SSAID = null;
            //string? body = null;
            //var response = instance.ApiLoginRefreshPost(SSAID, body);
            //Assert.IsType<string>(response);
        }

        /// <summary>
        /// Test ApiLoginRegisterPost
        /// </summary>
        [Fact]
        public void ApiLoginRegisterPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //RegisterModel? registerModel = null;
            //instance.ApiLoginRegisterPost(registerModel);
        }
    }
}
