/*
 * ShopApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using ShopApi.Client.Client;
using ShopApi.Client.Api;
// uncomment below to import models
//using ShopApi.Client.Model;

namespace ShopApi.Client.Test.Api
{
    /// <summary>
    ///  Class for testing ProductApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ProductApiTests : IDisposable
    {
        private ProductApi instance;

        public ProductApiTests()
        {
            instance = new ProductApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ProductApi
            //Assert.IsType<ProductApi>(instance);
        }

        /// <summary>
        /// Test ApiProductAddProductPost
        /// </summary>
        [Fact]
        public void ApiProductAddProductPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Product? product = null;
            //instance.ApiProductAddProductPost(product);
        }

        /// <summary>
        /// Test ApiProductGetAllProductsGet
        /// </summary>
        [Fact]
        public void ApiProductGetAllProductsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.ApiProductGetAllProductsGet();
        }

        /// <summary>
        /// Test ApiProductGetAllProductsTestOpenApiGenerateGet
        /// </summary>
        [Fact]
        public void ApiProductGetAllProductsTestOpenApiGenerateGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.ApiProductGetAllProductsTestOpenApiGenerateGet();
        }

        /// <summary>
        /// Test ApiProductGetProductByBarcodeGet
        /// </summary>
        [Fact]
        public void ApiProductGetProductByBarcodeGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string? barcode = null;
            //var response = instance.ApiProductGetProductByBarcodeGet(barcode);
            //Assert.IsType<Collection<Product>>(response);
        }

        /// <summary>
        /// Test ApiProductGetProductFromOpenFoodFactsGet
        /// </summary>
        [Fact]
        public void ApiProductGetProductFromOpenFoodFactsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string? barcode = null;
            //var response = instance.ApiProductGetProductFromOpenFoodFactsGet(barcode);
            //Assert.IsType<Product>(response);
        }

        /// <summary>
        /// Test ApiProductInitProductFromCSVPost
        /// </summary>
        [Fact]
        public void ApiProductInitProductFromCSVPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.ApiProductInitProductFromCSVPost();
        }

        /// <summary>
        /// Test ApiProductTestApiDirectlyGet
        /// </summary>
        [Fact]
        public void ApiProductTestApiDirectlyGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.ApiProductTestApiDirectlyGet();
        }
    }
}
