/*
 * ShopApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ShopApi.Client.Model;
using ShopApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ShopApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing Barcode
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BarcodeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Barcode
        //private Barcode instance;

        public BarcodeTests()
        {
            // TODO uncomment below to create an instance of Barcode
            //instance = new Barcode();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Barcode
        /// </summary>
        [Fact]
        public void BarcodeInstanceTest()
        {
            // TODO uncomment below to test "IsType" Barcode
            //Assert.IsType<Barcode>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'ProductId'
        /// </summary>
        [Fact]
        public void ProductIdTest()
        {
            // TODO unit test for the property 'ProductId'
        }

        /// <summary>
        /// Test the property 'Product'
        /// </summary>
        [Fact]
        public void ProductTest()
        {
            // TODO unit test for the property 'Product'
        }
    }
}
