/*
 * ShopApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ShopApi.Client.Model;
using ShopApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ShopApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing ELoginType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ELoginTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ELoginType
        //private ELoginType instance;

        public ELoginTypeTests()
        {
            // TODO uncomment below to create an instance of ELoginType
            //instance = new ELoginType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ELoginType
        /// </summary>
        [Fact]
        public void ELoginTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" ELoginType
            //Assert.IsType<ELoginType>(instance);
        }
    }
}
