/*
 * ShopApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ShopApi.Client.Model;
using ShopApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ShopApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing RegisterModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RegisterModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RegisterModel
        //private RegisterModel instance;

        public RegisterModelTests()
        {
            // TODO uncomment below to create an instance of RegisterModel
            //instance = new RegisterModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RegisterModel
        /// </summary>
        [Fact]
        public void RegisterModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" RegisterModel
            //Assert.IsType<RegisterModel>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Surname'
        /// </summary>
        [Fact]
        public void SurnameTest()
        {
            // TODO unit test for the property 'Surname'
        }

        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Fact]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Fact]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }

        /// <summary>
        /// Test the property 'ConfirmPassword'
        /// </summary>
        [Fact]
        public void ConfirmPasswordTest()
        {
            // TODO unit test for the property 'ConfirmPassword'
        }
    }
}
