/*
 * ShopApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ShopApi.Client.Model;
using ShopApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ShopApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing RoleForUser
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RoleForUserTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RoleForUser
        //private RoleForUser instance;

        public RoleForUserTests()
        {
            // TODO uncomment below to create an instance of RoleForUser
            //instance = new RoleForUser();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RoleForUser
        /// </summary>
        [Fact]
        public void RoleForUserInstanceTest()
        {
            // TODO uncomment below to test "IsType" RoleForUser
            //Assert.IsType<RoleForUser>(instance);
        }

        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }

        /// <summary>
        /// Test the property 'UserRoleId'
        /// </summary>
        [Fact]
        public void UserRoleIdTest()
        {
            // TODO unit test for the property 'UserRoleId'
        }

        /// <summary>
        /// Test the property 'User'
        /// </summary>
        [Fact]
        public void UserTest()
        {
            // TODO unit test for the property 'User'
        }

        /// <summary>
        /// Test the property 'UserRole'
        /// </summary>
        [Fact]
        public void UserRoleTest()
        {
            // TODO unit test for the property 'UserRole'
        }
    }
}
